### ISSUE TITLE
Hello How TO Compile with boost 1.69 or 1.70 ?

### ISSUE THREAD

**Issue by javashin** [MageSlayer/paludis-gentoo-overlay#2]
https://gist.github.com/javashin/48990f2b68be8cef74c88ed5edfb09aa

**Comment by MageSlayer** [comment]
I'll look into it.
https://bugs.gentoo.org/653878 might help.
BTW, which version of cmake do you use?

**Comment by javashin** [comment]
last version dev-util/cmake-3.14.5::gentoo and thanks.

**Comment by javashin** [comment]
im not trying to build paludis with python anymore works fine without python bindings
