### ISSUE TITLE
Why paludis takes so long to emerge gentoo-sources

### ISSUE THREAD

**Issue by javashin** [MageSlayer/paludis-gentoo-overlay#4]
paludis take ages to emerge gentoo-sources i dont like this , can be solved ?

**Comment by MageSlayer** [comment]
Well. It has quite a lot of files to emerge / hash (around 70000).
I am pretty sure it can be done in parallel, but is it really worth it?

**Comment by javashin** [comment]
yeah but portage does this very fast , and paludis stuck forever doing this anyway is better if i use portage for gentoo-sources and paludis for everything else , thanks for reply
